### PR TITLE
Added gp function and cookbook, removed functions gp-set,gp-u…

### PR DESCRIPTION
**Pull request by mmaul**
`gp-set`,`gp-unset`, `gp-clear` removed and replaced by `gp <command> &rest args`. Tests for issue 8 and 21 have been updated and should cover these changes. Also including the Ipython notebook and HTML output in the docs directory.

### CODE REVIEW

**Comment by guicho271828** [comment]
Excellent work! Could you rewrite it into two commits? Then I'll merge it immediately. (no need to make separate pullreqs)

**Comment by guicho271828** [comment]
Sorry for forgetting this for a while. merged now!

**Comment by mmaul** [comment]
No problem. I expect eazy-opencl has been keeping you busy, it looks really
cool.
I've kinda wondered if it might be usef to add open-cl operations to
mgl-mat which would be quite handy.

**Comment by guicho271828** [comment]
regarding opencl stuff, actually I found a better person specialized in GPU computing (@gos-k) who I personally get to know recently. He is a professional GPU programmer who used to play with CUDA assembly, PS3 and a lot more minor compute environments. He is now doing some higher-level stuff in https://github.com/gos-k/oclcl . I've been busy for my research papers

**Pull request merged**
